### ISSUE TITLE
リソース設計

### ISSUE THREAD

**Issue by YukiWatanabe824** [YukiWatanabe824/MAAKS#11]
## エレベーターピッチ & ペーパープロトタイプ
- エレベーターピッチ
https://bootcamp.fjord.jp/products/15298
- ペーパープロトタイプ
https://bootcamp.fjord.jp/products/15434

### 技術構成
こちらに記載しています。
https://github.com/YukiWatanabe824/MAAKS/wiki/Technology-Stack

サービス上のマップ表示はMapBox社のAPIを使用予定です。

### ユーザー管理周辺
deviseでのユーザー管理とomniauth-gemを使用したGoogle認証を実装する予定です。

## リソース設計
| method | path | description |
| --- | --- | --- |
| GET | / | トップページに遷移 |
| GET | /spots/{id} | スポットを表示する |
| GET | /spots/new | スポット作成ページを表示する |
| POST | /spots | スポットを作成する |
| GET | /spots/{id}/edit | スポット編集ページを表示する |
| PATCH | /spots/{id} | スポットを編集する |
| DELETE | /spots/{id} | スポットを削除する |
| GET | /users/{id} | ユーザーアカウントページを表示する |
| GET | /users/{id}/edit | アカウント編集ページを表示する(本人のみ) |
| PATCH | /users/{id} | アカウント情報を更新(本人のみ) |
| DELETE | /users/{id} | アカウント情報を削除(本人のみ) |
| GET | /users/sign_in | ログインページを表示する |
| その他 | deviseが生成するURLを利用 | サインアップ、ログイン、ログアウト |
| GET | /auth/:provider/callback | OAuth 2.0によるGoogleログイン処理、ユーザー作成処理 |
| GET | /tos | terms of service(利用規約)を表示する |
| GET | /privercy_policy | プライバシポリシーを表示する |

データ設計は[こちら](#12 )

**Comment by maedana** [comment]
地図TileはMapBoxでいいと思いますが、商用無料のサービスもあるかなーと思います。参考
https://drawtrail.net/map-tile-summary/

[追記] 色々事前検討はしていた様子ですねー。
https://bootcamp.fjord.jp/reports/75616
なので上記忘れて頂いてい大丈夫です :sweat_smile: 

あと地図のjsライブラリはMapBoxのものを利用する想定かと思いますが、過去に使ったことがあるものですと
https://leafletjs.com
がシンプルで好みでしたー。

https://docs.mapbox.com/help/glossary/leaflet/
を見るとMapbox.jsはleafletをラップしたものなのかもですね。

以上ご参考までに。

**Comment by YukiWatanabe824** [comment]
@maedana 
日報まで確認ありがとうございます！
 地図については最終的にMapBoxにした経緯を日報に書いていなかったのですが、日報でYOLPに決めたあとにYOLPには地図そのものはないことを知りまして、その後Yahoo!が使用しているMapBoxとGoogleMapを比較して決めたような流れでした。

jsライブラリの情報もありがとうございます！参考にしていきます😄
