### ISSUE TITLE
データ設計

### ISSUE THREAD

**Issue by YukiWatanabe824** [YukiWatanabe824/MAAKS#12]
## エレベーターピッチ & ペーパープロトタイプ
- エレベーターピッチ
https://bootcamp.fjord.jp/products/15298
- ペーパープロトタイプ
https://bootcamp.fjord.jp/products/15434

### 技術構成
こちらに記載しています。
https://github.com/YukiWatanabe824/MAAKS/wiki/Technology-Stack

サービス上のマップ表示はMapBox社のAPIを使用予定です。

### スポットの表示
Spotに緯度経度のデータを保持することで、その情報をもとにマップ上にピンを立てる機能実装を予定しています。

## データ設計
```mermaid
erDiagram
    Users ||--o{ Spots : ""

    Users {
        integer id PK
				string name "null: false"
        string uid
        string avater_url
				string password "null: false"
				timestamp created_at "null: false"
				timestamp updated_at "null: false"
    }
    Spots {
        integer id PK
				integer user_id FK "null: false"
				string title "null: false"
				string accident_type "null: false"
        string contents "null: false"
        date accident_date "null: false"
				float longitude "null: false"
				float latitude "null: false"
				timestamp created_at "null: false"
				timestamp updated_at "null: false"
    }
```

リソース設計は[こちら](#11)

**Comment by maedana** [comment]
Spots#type, Spots#dateはPostgreSQLの予約語ではないものの一般名過ぎるようにも思いますね。特にSpots#dateの方はSQLでは一般的に予約語のようなので避けたほうがいい命名かなと思います。

なお、それぞれ目的のカラムなのでしょう?

追記 PostgreSQLの予約語のドキュメント
https://pgsql-jp.github.io/current/html/sql-keywords-appendix.html

**Comment by maedana** [comment]
Spots#longitude, Spots#latitudeはStringだと位置情報絡みのクエリ発行するときにちゃんとパフォーマンス出るのか心配ですね。floatの方が適切ではないかと思いました。ただ、そこまで大量のデータがすぐに登録されるわけでもなさそうですし、実際は誤差の範疇かもしれません。

もっとちゃんとやるなら、PostGIS拡張を入れてgeometry, geography型が使えるようにするとよいかも? しかし今回の用途ではオーバースペックになりそうではありますし、そこまでしなくていいとは思います。あくまでもご参考までに。以下のような各種専用関数も使えて、複雑なことをしようとすると必要になります。(例えばある領域に現在地が入っているかどうか、とか、半径xx内のSpotを探してくる、とか)

以下の記事が詳しくて比較的わかりやすいですねー。
https://zenn.dev/boiledorange73/books/caea8d4c77dbba2e23a0/viewer/testing

以下も位置情報扱うなら頭に入れておきたいです。ちゃんと意識せずに位置情報扱うと実はズレていたりとかするかもです。
https://zenn.dev/boiledorange73/books/caea8d4c77dbba2e23a0/viewer/srs

**Comment by maedana** [comment]
Spotに写真とか動画とかは不要なんですかね? 例えば土砂崩れがあった、とかだと可能なら現地の様子がわかるとよりいいのかなーって思いました。なお、もし必要だとしても最初は必ずしもなくてもいいかなと思いますし、あとから追加でもいいとは思います。

**Comment by YukiWatanabe824** [comment]
ご確認ありがとうございます！

> Spots#type, Spots#dateはPostgreSQLの予約語ではないものの一般名過ぎるようにも思いますね。特にSpots#dateの方はSQLでは一般的に予約語のようなので避けたほうがいい命名かなと思います。
なお、それぞれ目的のカラムなのでしょう?

こちらはそれぞれ以下の役割を想定したカラムになっています。
- Spots#type...事故の原因の種類(路面が悪い、車との事故など)。ひとつの原因に集中しているエリアを走行するときに、特に気をつけるべきことがわかるようになります。
- Spots#date...事故の日時。スポットの登録と事故のタイミングは一致しないことが想定されるため。

どちらも一般的すぎましたね。カラムの目的と一致する命名に変更したいと思います。

> Spots#longitude, Spots#latitudeはStringだと位置情報絡みのクエリ発行するときにちゃんとパフォーマンス出るのか心配ですね。floatの方が適切ではないかと思いました。ただ、そこまで大量のデータがすぐに登録されるわけでもなさそうですし、実際は誤差の範疇かもしれません。

float型に変更するようにいたします
位置情報のズレについても認識していませんでしたので助かります！

> Spotに写真とか動画とかは不要なんですかね?

画像等のメディアファイルは検討して一旦なしでいこうと考えました。土砂崩れの写真とかならいいのですが、事故の怪我の写真などアップされてしまうと視聴者としてはつらいものがあるかなーと思案しています💦そういう画像をあげてしまうサイクリストは一定数いる印象です。

**Comment by maedana** [comment]
> 事故の怪我の写真などアップされてしまうと視聴者としてはつらいものがある

確かに...。その観点はなかったのですが納得しました。

**Comment by YukiWatanabe824** [comment]
アプリ側の修正も完了しましたのでcloseいたします〜
